import Modal from './Modal';

interface ABCScenarioDialogProps {
  handleClose: () => void;
  isOpen: boolean;
}

function ABCScenarioDialog({ handleClose, isOpen }: ABCScenarioDialogProps) {
  return (
    <Modal
      handleClose={handleClose}
      isOpen={isOpen}
      title="How to use the ABC Simulator"
    >
      <p className="font-inter text-lg text-neon-light text-center p-4">
        Use the ABC simulator to see how your configurations react to simulated
        market environments. Get started by doing the following:
        <ul className="list-inside list-disc font-inter">
          <li className="py-5">
            <b>Choose a Market Scenario,</b> either <i>Bullish</i> or
            <i>Bearish</i>. This will modify the 3 initial steps implemented to
            begin your economy’s story.
          </li>
          <li className="py-5">
            <b>Select a Reserve Balance.</b> This defines where your steps begin
            and the range of your X-axis. Clicking LAUNCH will use the amount of
            Hatch funds raised with your Commons Tribute setting.
          </li>
          <li className="py-5">
            <b>Add a Step,</b> to place a buy or sell transaction on your ABC.
            This will create a new step on your curve. Take note of the 3 steps
            already generated by your Market Scenario.
          </li>
        </ul>
      </p>
    </Modal>
  );
}

export default ABCScenarioDialog;
